name: ' Increment Version Number'

run-name: "Increment Version Number in [${{ github.ref_name }}]"

on:
  workflow_dispatch:
    inputs:
      projects:
        description: Comma-separated list of project name patterns if the repository is setup for multiple projects (default is * for all projects)
        required: false
        default: '*'
      versionNumber:
        description: New Version Number in main branch. Use Major.Minor[.Build] for absolute change, use +Major.Minor[.Build] for incremental change.
        required: false
        default: ''
      updateDependencies:
        description: Update dependency version numbers in app.json?
        type: boolean
        default: true
      directCommit:
        description: Direct Commit?
        type: boolean
        default: false
      useGhTokenWorkflow:
        description: Use GhTokenWorkflow for PR/Commit?
        type: boolean
        default: false

permissions:
  actions: read
  contents: write
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  IncrementVersionNumber:
    needs: [ ]
    runs-on: [ windows-latest ]
    steps:
      - name: Dump Workflow Information
        uses: freddydk/AL-Go/Actions/DumpWorkflowInfo@trimit
        with:
          shell: powershell

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Initialize the workflow
        id: init
        uses: freddydk/AL-Go/Actions/WorkflowInitialize@trimit
        with:
          shell: powershell

      - name: Read settings
        uses: freddydk/AL-Go/Actions/ReadSettings@trimit
        with:
          shell: powershell

      - name: Read secrets
        id: ReadSecrets
        uses: freddydk/AL-Go/Actions/ReadSecrets@trimit
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'TokenForPush'
          useGhTokenWorkflowForPush: '${{ github.event.inputs.useGhTokenWorkflow }}'

      - name: Increment Version Number
        uses: freddydk/AL-Go/Actions/IncrementVersionNumber@trimit
        with:
          shell: powershell
          token: ${{ steps.ReadSecrets.outputs.TokenForPush }}
          projects: ${{ github.event.inputs.projects }}
          versionNumber: ${{ github.event.inputs.versionNumber }}
          updateDependencies: ${{ github.event.inputs.updateDependencies }}
          directCommit: ${{ github.event.inputs.directCommit }}

      - name: Finalize the workflow
        if: always()
        uses: freddydk/AL-Go/Actions/WorkflowPostProcess@trimit
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: powershell
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          currentJobContext: ${{ toJson(job) }}
